# Generated by Django 3.0.5 on 2021-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210110_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
