# Generated by Django 3.0.5 on 2021-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210110_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(default='Titulo del Trabajo', max_length=50),
            preserve_default=False,
        ),
    ]
