# Generated by Django 3.0.5 on 2021-01-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20210110_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='demora',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
