# Generated by Django 3.0.5 on 2021-01-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20210110_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
