# Generated by Django 3.0.5 on 2021-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20210111_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='preciofijo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
